#!/bin/bash

rostopic pub /arm_controller/command \
control_msgs/FollowJointTrajectoryActionGoal

#!trajectory_msgs/JointTrajectory \

#!'{joint_names: ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"], points: [{positions:[1, 1, 1, 0.5, 0.5, 0.5], time_from_start: [1.0,0.0]}]}' -1

'{header: {seq: 0, stamp: {secs: 0, nsecs: 0 }, frame_id: "world"}, name: ["shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint"], position: [1, 1, 1, 0.5, 0.5, 0.5], velocity: [0, 0, 0, 0, 0, 0], effort: [0, 0, 0, 0, 0, 0]}'

#!'{header: 'auto', name: ["joint_1, joint_2, joint_3, joint_4, joint_5, joint_6"], position: [1, 1, 1, 0.5, 0.5, 0.5], velocity: [0, 0, 0, 0, 0, 0], effort: [0, 0, 0, 0, 0, 0]}'


#!{seq: , stamp: {secs: , nsecs: }, frame_id: ""} 


